### ISSUE TITLE
Message Queue

### ISSUE THREAD

**Issue by RichardSWheatley** [SiliconLabs/bluetooth_stack_features#2]
When performing fast external signaling in interrupts, some of the indicates or notifies do not get across.

It is not the interrupt since the ISR is being handled.
It appears as though the BLE messages are not being sent.

Is there a queue implemented in the BLE stack for successive outgoing external signal messages?

**Comment by anhirvon** [comment]
The signal by calling sl_bt_external_signal() just raises one bit. So a successive call of it should result in only one BGAPI event sl_bt_evt_system_external_signal if I got the question correctly.
